services:
  frontend:
    build:
      context: ./images-gallery/image-gallery-app-frontend
    image: images-gallery-frontend
    container_name: image-gallery-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # file watcher works on mounted volumes
      - WATCHPACK_POLLING=true # helps webpack
      - WDS_SOCKET_PORT=3000 # CRA websocket through Docker
      - HOST=0.0.0.0 # bind externally
    volumes:
      - ./images-gallery/image-gallery-app-frontend:/app
      - /app/node_modules # keep container's node_modules
    depends_on:
      - api

  api:
    build: ./images-gallery/api
    image: images-gallery-api
    container_name: image-gallery-api
    ports:
      - "5050:5050"
    volumes:
      - ./images-gallery/api:/app
      - /app/node_modules
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-strong-db-password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:very-strong-db-password@mongo:27017/admin?authSource=admin"
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "mongoexpressuser"
      ME_CONFIG_BASICAUTH_PASSWORD: "very-strong-db-password"
    depends_on:
      - mongo
volumes:
  mongodb_data:
